### ISSUE TITLE
Unable to build maven- giving parent error

### ISSUE THREAD

**Issue by pulkit11** [PredixDev/predix-microservice-cf-jsr#3]
Hello,

Please find the stack trace and let me know where i am doing mistake. I downloaded the project and trying to build it.

SFO1502637645M:predix-microservice-cf-jsr-master 502637645$ mvn install
[INFO] Scanning for projects...
Downloading: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-parent/1.2.3.RELEASE/spring-boot-starter-parent-1.2.3.RELEASE.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.ge.predix.solsvc:predix-microservice-cf-jsr:1.1.6: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:1.2.3.RELEASE from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org: unknown error and 'parent.relativePath' points at no local POM @ line 10, column 10
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]  
[ERROR]   The project com.ge.predix.solsvc:predix-microservice-cf-jsr:1.1.6 (/Users/502637645/Documents/mydev/predix-microservice-cf-jsr-master/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.ge.predix.solsvc:predix-microservice-cf-jsr:1.1.6: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:1.2.3.RELEASE from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org: unknown error and 'parent.relativePath' points at no local POM @ line 10, column 10: Unknown host repo.maven.apache.org: unknown error -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

Thanks,
Pulkit

**Comment by turnerth** [comment]
I tried that and it worked, the key to your error is this
Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:1.2.3.RELEASE from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org: 

So, that means you might have an invalid ~/.m2/settings.xml.  Or you are accessing the internet through a proxy server which is blocking you.  

Please read the set up instructions to help you get set up.

**Comment by pulkit11** [comment]
Hello,

I am GE employee and under GE network.

Thanks,
Pulkit

**Comment by YehangHan** [comment]
any updates?

**Comment by gstroup** [comment]
We can build this project without errors.  Please double check your maven settings.xml file, and make sure your credentials are correct, so maven can pull dependencies from artifactory.

**Comment by YehangHan** [comment]
fixed it by removing the http://  in the proxy server domain
