### ISSUE TITLE
POM file is missing relative path to parent project.

### ISSUE THREAD

**Issue by ghost** [PredixDev/predix-microservice-cf-jsr#4]
The pom.xml file is missing the relative path to the parent project, the code says to lookup parent from repository, which I am confused on what that means. Do I need to include a link to the GitHub repo?

**Comment by turnerth** [comment]
There's a few references to parent and I'm not sure which you mean.  Could you point to the line of code you are referring to?

The parent in the pom.xml is referring to the spring boot parent.  That'll get downloaded by maven.  It's a parent dependency as opposed to a child dependency.

**Comment by ghost** [comment]
Line 10 of the pom.xml file, it asks to lookup parent from repository. 
So do I have to point to it from my files: C:\Users\212458557\.m2\repository\org\springframework\boot\spring-boot-starter-parent\1.2.3.RELEASE/spring-boot-starter-parent-1.2.3RELEASE.pom.lastUpdated

**Comment by turnerth** [comment]
You'll need to read about how Maven works.  In general, maven will see the GroupId and ArtifactId and Version and download the spring-boo-starter-parent jar to your local Maven repository.  

Please read this and this...
https://www.predix.io/resources/tutorials/tutorial-details.html?tutorial_id=1560&tag=1608&journey=Development%20tools%20and%20tips&resources=1565,1560
https://www.predix.io/resources/tutorials/tutorial-details.html?tutorial_id=1565&tag=1608&journey=Development%20tools%20and%20tips&resources=1565,1560
